export const DISPLAY_MAIN_ERROR = 'DISPLAY_MAIN_ERROR';
export const APP_COMPONTENT_LOADED = 'APP_COMPONTENT_LOADED';
export const UPDATE_APP_LAYOUT_STATE = 'UPDATE_APP_LAYOUT_STATE';
export const UPDATE_APP_CONTRIBUTE_STATE = 'UPDATE_APP_CONTRIBUTE_STATE';
