export const DISPLAY_MAIN_ERROR = 'DISPLAY_MAIN_ERROR';
export const APP_COMPONTENT_LOADED = 'APP_COMPONTENT_LOADED';
export const UPDATE_APP_CONTRIBUTE_STATE = 'UPDATE_APP_CONTRIBUTE_STATE';
export const APP_LAYOUT_CHANGE_COMPONENT_VISIBILITY = 'APP_LAYOUT_CHANGE_COMPONENT_VISIBILITY';
export const APP_LAYOUT_SHOW_COMPONENT = 'APP_LAYOUT_SHOW_COMPONENT';
export const APP_LAYOUT_HIDE_COMPONENT = 'APP_LAYOUT_HIDE_COMPONENT';
