export const BUILDER_ADD_APP_ITEM_ATTACHMENT = 'BUILDER_ADD_APP_ITEM_ATTACHMENT';
export const BUILDER_REMOVE_APP_ITEM_ATTACHMENT = 'BUILDER_REMOVE_APP_ITEM_ATTACHMENT';
export const UPDATE_BUILDER_APP_SHARE = 'UPDATE_BUILDER_APP_SHARE';
export const UPDATE_BUILDER_APP_SHARE_STATUS = 'UPDATE_BUILDER_APP_SHARE_STATUS';
export const CHANGE_BUIDER_DIALOG = 'CHANGE_BUIDER_DIALOG';
export const UPDATE_BUILDER_SAVE_STATUS = 'UPDATE_BUILDER_SAVE_STATUS';
