// App Item
export const UPDATE_ITEM_APP_ITEM = 'UPDATE_ITEM_APP_ITEM';
export const UPDATE_ITEM_APP_ITEM_TITLE = 'UPDATE_ITEM_APP_ITEM_TITLE';
export const UPDATE_ITEM_APP_ITEM_SUBTITLE = 'UPDATE_ITEM_APP_ITEM_SUBTITLE';

// Webmap Item
export const UPDATE_ITEM_WEBMAP_ITEM = 'UPDATE_ITEM_WEBMAP_ITEM';
export const UPDATE_ITEM_WEBMAP_ITEM_TITLE = 'UPDATE_ITEM_WEBMAP_ITEM_TITLE';
export const UPDATE_ITEM_WEBMAP_DATA = 'UPDATE_ITEM_WEBMAP_DATA';
export const UPDATE_ITEM_WEBMAP_CROWDSOURCE_LAYER = 'UPDATE_ITEM_WEBMAP_CROWDSOURCE_LAYER';

// Feature Service Item
export const UPDATE_ITEM_FEATURE_SERVICE_ITEM = 'UPDATE_ITEM_FEATURE_SERVICE_ITEM';
export const UPDATE_ITEM_FEATURE_SERVICE_ITEM_TITLE = 'UPDATE_ITEM_FEATURE_SERVICE_ITEM_TITLE';
export const UPDATE_ITEM_FEATURE_SERVICE_DEFINITION = 'UPDATE_ITEM_FEATURE_SERVICE_DEFINITION';
export const UPDATE_ITEM_FEATURE_SERVICE_LAYER_DEFINITION = 'UPDATE_ITEM_FEATURE_SERVICE_LAYER_DEFINITION';
