// App Item
export const UPDATE_ITEM_APP_ITEM = 'UPDATE_ITEM_APP_ITEM';
export const UPDATE_ITEM_APP_ITEM_TITLE = 'UPDATE_ITEM_APP_ITEM_TITLE';

// Webmap Item
export const UPDATE_ITEM_WEBMAP_ITEM = 'UPDATE_ITEM_WEBMAP_ITEM';
export const UPDATE_ITEM_WEBMAP_ITEM_TITLE = 'UPDATE_ITEM_WEBMAP_ITEM_TITLE';

// Feature Service Item
export const UPDATE_ITEM_FEATURE_SERVICE_ITEM = 'UPDATE_ITEM_FEATURE_SERVICE_ITEM';
export const UPDATE_ITEM_FEATURE_SERVICE_ITEM_TITLE = 'UPDATE_ITEM_FEATURE_SERVICE_ITEM_TITLE';
