export const UPDATE_MAP_REFERENCES = 'UPDATE_MAP_REFERENCES';
export const UPDATE_MAP_FEATURES_IN_EXTENT = 'UPDATE_MAP_FEATURES_IN_EXTENT';
export const UPDATE_MAP_SELECTED_FEATURES = 'UPDATE_MAP_SELECTED_FEATURES';
