// OAuth Settings
export const UPDATE_SETTINGS_OAUTH = 'UPDATE_SETTINGS_OAUTH';

// Component Settings

// Common Component
export const UPDATE_SETTINGS_COMMON_PARTICIPATE_SHORT = 'UPDATE_SETTINGS_COMMON_PARTICIPATE_SHORT';
export const UPDATE_SETTINGS_COMMON_EXPLORE_TEXT = 'UPDATE_SETTINGS_COMMON_EXPLORE_TEXT';

// Intro Component
export const UPDATE_SETTINGS_INTRO_TITLE = 'UPDATE_SETTINGS_INTRO_TITLE';
export const UPDATE_SETTINGS_INTRO_SUBTITLE = 'UPDATE_SETTINGS_INTRO_SUBTITLE';

// Header Component
export const UPDATE_SETTINGS_HEADER_TITLE = 'UPDATE_SETTINGS_HEADER_TITLE';
export const UPDATE_SETTINGS_HEADER_LOGO_LINK = 'UPDATE_SETTINGS_HEADER_LOGO_LINK';

// Map Component
export const UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER_ID = 'UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER_ID';
export const UPDATE_SETTINGS_MAP_WEBMAP_ID = 'UPDATE_SETTINGS_MAP_WEBMAP_ID';

// Layout Settings
export const UPDATE_LAYOUT_ID = 'UPDATE_LAYOUT_ID';
