// OAuth Settings
export const UPDATE_SETTINGS_OAUTH = 'UPDATE_SETTINGS_OAUTH';

// Component Settings

// Common Component
export const UPDATE_SETTINGS_COMMON_PARTICIPATE_SHORT = 'UPDATE_SETTINGS_COMMON_PARTICIPATE_SHORT';
export const UPDATE_SETTINGS_COMMON_EXPLORE_TEXT = 'UPDATE_SETTINGS_COMMON_EXPLORE_TEXT';
export const UPDATE_SETTINGS_COMMON_SHARING_SERVICES = 'UPDATE_SETTINGS_COMMON_SHARING_SERVICES';
export const UPDATE_SETTINGS_COMMON_SHARING_TWITTER = 'UPDATE_SETTINGS_COMMON_SHARING_TWITTER';

// Contribute Component
export const UPDATE_SETTINGS_CONTRIBUTE_PARTICIPATION_ALLOWED = 'UPDATE_SETTINGS_CONTRIBUTE_PARTICIPATION_ALLOWED';
export const UPDATE_SETTINGS_CONTRIBUTE_LOGIN_OPTIONS = 'UPDATE_SETTINGS_CONTRIBUTE_LOGIN_OPTIONS';
export const UPDATE_SETTINGS_CONTRIBUTE_TERMS_AND_CONDITIONS = 'UPDATE_SETTINGS_CONTRIBUTE_TERMS_AND_CONDITIONS';

// Intro Component
export const UPDATE_SETTINGS_INTRO_TITLE = 'UPDATE_SETTINGS_INTRO_TITLE';
export const UPDATE_SETTINGS_INTRO_SUBTITLE = 'UPDATE_SETTINGS_INTRO_SUBTITLE';
export const UPDATE_SETTINGS_INTRO_BACKGROUND = 'UPDATE_SETTINGS_INTRO_BACKGROUND';

// Header Component
export const UPDATE_SETTINGS_HEADER_TITLE = 'UPDATE_SETTINGS_HEADER_TITLE';
export const UPDATE_SETTINGS_HEADER_LOGO_TYPE = 'UPDATE_SETTINGS_HEADER_LOGO_TYPE';
export const UPDATE_SETTINGS_HEADER_LOGO_URL = 'UPDATE_SETTINGS_HEADER_LOGO_URL';
export const UPDATE_SETTINGS_HEADER_LOGO_LINK = 'UPDATE_SETTINGS_HEADER_LOGO_LINK';

// Map Component
export const UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER_ID = 'UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER_ID';
export const UPDATE_SETTINGS_MAP_WEBMAP_ID = 'UPDATE_SETTINGS_MAP_WEBMAP_ID';
export const UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER_VISIBLE_FEATURES_QUERY_ADD = 'UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER_VISIBLE_FEATURES_QUERY_ADD';
export const UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER_VISIBLE_FEATURES_QUERY_REMOVE = 'UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER_VISIBLE_FEATURES_QUERY_REMOVE';

// Layout Settings
export const UPDATE_LAYOUT_ID = 'UPDATE_LAYOUT_ID';
