// Component Settings

// Intro Component
export const UPDATE_SETTINGS_INTRO_TITLE = 'UPDATE_SETTINGS_INTRO_TITLE';
export const UPDATE_SETTINGS_INTRO_SUBTITLE = 'UPDATE_SETTINGS_INTRO_SUBTITLE';

// Header Component
export const UPDATE_SETTINGS_HEADER_TITLE = 'UPDATE_SETTINGS_HEADER_TITLE';

// Map Component
export const UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER = 'UPDATE_SETTINGS_MAP_CROWDSOURCE_LAYER';
export const UPDATE_SETTINGS_MAP_WEBMAP_ID = 'UPDATE_SETTINGS_MAP_WEBMAP_ID';

// Layout Settings
export const UPDATE_LAYOUT_ID = 'UPDATE_LAYOUT_ID';
