export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const USER_START_LOGIN = 'USER_START_LOGIN';
export const USER_FINISH_LOGIN = 'USER_FINISH_LOGIN';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
